apiVersion: apps/v1
kind: Deployment
metadata:
  name: slogtester
  labels:
    app: slogtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slogtester
  template:
    metadata:
      labels:
        app: slogtester
    spec:
      containers:
      - image: gcr.io/metal-tile-dev1/sinmetal/slogtester/master:latest
        name: slogtester