apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: slogtester
  name: slogtester
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: slogtester
    spec:
      containers:
      - image: gcr.io/metal-tile-dev1/sinmetal/slogtester:latest
        name: slogtester